Repository FRONT-END-BOOTCAMP-PLUS-5/Gamdo, pull requests merged in 2025-07, with the labels that each got.

#4 feat: 영화 아이디를 이용한 영화 조회 API 연동 완료
  app/api/(anon)/movie/route.ts
  backend/application/movie/GetMovieDetailsUseCase.ts
  backend/infrastructure/tmdb/TmdbApi.ts
  package-lock.json
  package.json
  utils/supabase/client.ts
Labels: 🔥BE, 💫 FEAT

#7 Feature/recommender 개발
  app/api/(anon)/weather/route.ts
  backend/application/.gitkeep
  backend/application/recommender/GetMovieWeatherUseCase.ts
  backend/domain/entities/.gitkeep
  backend/domain/entities/recommender/weather.ts
  backend/domain/repositories/.gitkeep
  backend/domain/repositories/recommender/weather.ts
  backend/infrastructure/repositories/.gitkeep
  backend/infrastructure/repositories/recommender/weather.ts
  utils/supabase/recommender/coordinate-converter.ts
  utils/supabase/recommender/weather.ts
Labels: 🔥BE

#6 feat: 한줄평 POST API 구현 완료
  app/api/(anon)/review/route.ts
  backend/application/review/CreateReviewUseCase.ts
  backend/domain/entities/Review.ts
  backend/domain/repositories/ReviewRepository.ts
  backend/infrastructure/repositories/ReviewRepositoryImpl.ts
Labels: 🔥BE, 💫 FEAT

#12 feat: 한줄평 CRUD 구현 완료
  app/api/(anon)/movie/route.ts
  app/api/(anon)/review/route.ts
  app/api/(anon)/route.ts
  backend/application/movie/GetMovieDetailsUseCase.ts
  backend/application/review/CreateReviewUseCase.ts
  backend/application/review/DeleteReviewUseCase.ts
  backend/application/review/GetReviewUseCase.ts
  backend/application/review/UpdateReviewUseCase.ts
  backend/domain/entities/Review.ts
  backend/domain/repositories/ReviewRepository.ts
  backend/infrastructure/repositories/ReviewRepositoryImpl.ts
  utils/tmdb/TmdbApi.ts
Labels: 🔥BE, 💫 FEAT

#23 회원 인증 로직 변경, api 경로 수정
  app/(anon)/signup/page.tsx
  app/api/(anon)/auth/logout/route.ts
  app/api/(anon)/auth/signin/route.ts
  app/api/(anon)/auth/signup/route.ts
  app/api/(anon)/user/email-exists/route.ts
  app/api/(anon)/user/nickname-exists/route.ts
  app/api/(anon)/user/route.ts
  app/middleware.ts
  backend/application/signin/usecases/SigninUsecase.ts
  backend/application/signup/usecases/CreateSignupUsecase.ts
  backend/application/user/dtos/UpdateUserInfoDto.ts
  backend/application/user/usecase/GetUserInfoUsecase.ts
  backend/application/user/usecase/UpdateUserInfoUsecase.ts
  backend/common/auth/cookies.ts
  backend/common/auth/verifyAuthTokens.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/SbUserRepository.ts
  utils/authPaths.ts
  utils/hash.ts
Labels: 🔥BE, 💫 FEAT

#26 폰트 추가, 헤더, 푸터 초기 세팅
  app/components/Footer.tsx
  app/components/Header.tsx
  app/components/index.ts
  app/globals.css
  app/layout.tsx
  app/page.tsx
  public/assets/icons/logo.svg
  public/assets/icons/profile.svg
  public/file.svg
  public/fonts/PretendardVariable.woff2
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: 🍀FE

#31 영화 저장 시스템 개발
  README.md
  app/api/(anon)/saves/movie-poster/route.ts
  app/api/(anon)/saves/route.ts
  app/movie-detail-test/page.tsx
  backend/application/saves/dtos/SaveMovieDto.ts
  backend/application/saves/usecases/SaveMovieUseCase.ts
  backend/domain/entities/saves/SavedMovie.ts
  backend/domain/repositories/saves/SavedMovieRepository.ts
  backend/infrastructure/saves/SavedMovieRepositoryImpl.ts
Labels: 🔥BE, 💫 FEAT

#37 chore: tailwind css 기본 설정
  app/components/Header.tsx
  app/globals.css
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  tailwind.config.js
Labels: 🍀FE, ⚙️ CHORE

#41 design: 추천페이지 퍼블리싱
  app/(anon)/recommender/page.tsx
  app/(anon)/recommender/pageTest.tsx
  app/globals.css
  package-lock.json
  public/assets/images/weather_rain.png
Labels: 💫 FEAT, 🍀FE

#44 fix: TMDB API 최신화에 따른 충돌 해결
  app/(anon)/recommender/page.tsx
  app/gemini-test/page.tsx
  backend/application/recommenders/dtos/GetMovieInfoDto.ts
  backend/application/recommenders/usecases/GetMovieInfoUseCase.ts
Labels: 🐞BUG, 🔥BE

#48 design: 추천페이지 UI 구현 및 컴포넌트 생성
  app/(anon)/recommender/components/Button.tsx
  app/(anon)/recommender/page.tsx
  app/(anon)/recommender/pageTest.tsx
  app/components/PosterCard.tsx
  app/globals.css
  public/assets/images/recommendBtnDesign.png
Labels: 📜 DOCS, 💫 FEAT, 🛠️ REFACTOR, 🍀FE, ⚙️ CHORE

#51 찜하기(볼래요) 백엔드 기능 구현, package.json 버전 롤백
  app/api/(anon)/saved-watch/route.ts
  backend/application/saved-watch/dtos/CreateSavedWatchDto.ts
  backend/application/saved-watch/usecases/CreateSavedWatchUsecase.ts
  backend/application/saved-watch/usecases/DeleteSavedWatchUsecase.ts
  backend/application/saved-watch/usecases/GetSavedWatchUsecase.ts
  backend/domain/entities/SavedWatch.ts
  backend/domain/repositories/SavedWatchRepository.ts
  backend/infrastructure/mappers/Mapper.ts
  backend/infrastructure/repositories/SbSavedWatchRepository.ts
  backend/infrastructure/types/database.ts
  package-lock.json
  package.json
Labels: 🐞BUG, 🔥BE, 💫 FEAT

#52 feat: 영화 상세정보 모달 ui 구현
  app/(anon)/movie-detail/components/Modal.tsx
  app/(anon)/movie-detail/components/MovieHeader.tsx
  app/(anon)/movie-detail/components/MoviePreviewInfo.tsx
  app/(anon)/movie-detail/components/MovieReviewList.tsx
  app/(anon)/recommanded/moviesMockData.ts
  app/(anon)/recommanded/page.tsx
  app/api/(anon)/movies/route.ts
  app/api/(anon)/route.ts
  app/components/Platform.ts
  app/components/index.ts
  backend/application/search/usecases/SearchMultiUseCase.ts
  backend/domain/repositories/movies/SearchRepository.ts
  backend/infrastructure/repositories/movies/MovieRepositoryImpl.ts
  backend/infrastructure/repositories/movies/SearchRepositoryImpl.ts
  public/assets/images/apple-tv.png
  public/assets/images/disney-plus.svg
  public/assets/images/netflix.png
  public/assets/images/tving.png
  public/assets/images/watcha.png
  public/assets/images/wavve.png
  utils/tmdb/TmdbApi.ts
Labels: 🐞BUG, 🔥BE, 💫 FEAT, 🛠️ REFACTOR, 🍀FE

#53 마이페이지 ui 수정
  app/mypage/components/CustomCalendarSection.tsx
  app/mypage/components/ProfileCard.tsx
  app/mypage/components/ReviewSummary.tsx
  app/mypage/components/SavedMoviesList.tsx
  app/mypage/page.tsx
  public/assets/images/sample_profile_image.png
Labels: 🍀FE

#54 마이페이지 경로 수정
  app/(anon)/mypage/components/CalendarSection.tsx
  app/(anon)/mypage/components/CustomCalendarSection.tsx
  app/(anon)/mypage/components/ProfileCard.tsx
  app/(anon)/mypage/components/ReviewSummary.tsx
  app/(anon)/mypage/components/SavedMoviesList.tsx
  app/(anon)/mypage/page.tsx
Labels: 🍀FE, ⚙️ CHORE

#55 fix: build 에러 해결
  app/api/(anon)/movies/[id]/route.ts
Labels: 🐞BUG

#57 feat: 공용 모달 컴포넌트 창 구현
  app/(anon)/movie-detail/components/MovieDetailModal.tsx
  app/api/(anon)/movie-like/route.ts
  app/components/Modal.tsx
Labels: 💫 FEAT, 🍀FE

#58 feat: 영화 상세보기 모달 UI/UX 완료
  app/(anon)/movie-detail/components/MoviePreviewInfo.tsx
  app/(anon)/movie-detail/components/MovieReviewList.tsx
Labels: 💫 FEAT, 🍀FE

#64 feat: 마이페이지 찜하기(볼래요) 구현, 파비콘/ 메타데이터 추가
  app/(anon)/mypage/components/ProfileCard.tsx
  app/(anon)/mypage/components/SavedMoviesList.tsx
  app/(anon)/mypage/components/SavedMoviesListModal.tsx
  app/(anon)/mypage/hooks/useSavedMovies.ts
  app/(anon)/mypage/page.tsx
  app/api/(anon)/saved-watch/route.ts
  app/components/PosterCard.tsx
  app/components/SkeletonUI.tsx
  app/components/index.ts
  app/constants/authPaths.ts
  app/layout.tsx
  backend/application/saved-watch/usecases/GetSavedWatchUsecase.ts
  backend/domain/repositories/SavedWatchRepository.ts
  backend/infrastructure/mappers/Mapper.ts
  backend/infrastructure/repositories/SbSavedWatchRepository.ts
  package-lock.json
  package.json
  public/assets/icons/favicon.ico
  public/assets/images/no_poster_image.png
Labels: 🔥BE, 💫 FEAT, 🛠️ REFACTOR, 🍀FE

#63 feat: 추천 페이지 모달 추가 및 UI 수정
  app/(anon)/recommender/components/TrendMovies.tsx
  app/(anon)/recommender/page.tsx
  public/assets/images/recommendBtnDesign.png
  public/assets/images/trendMovieImages/trendMovie01.webp
  public/assets/images/trendMovieImages/trendMovie02.webp
  public/assets/images/trendMovieImages/trendMovie03.webp
  public/assets/images/trendMovieImages/trendMovie04.webp
  public/assets/images/trendMovieImages/trendMovie05.webp
  public/assets/images/trendMovieImages/trendMovie06.webp
  public/assets/images/trendMovieImages/trendMovie07.webp
  public/assets/images/trendMovieImages/trendMovie08.webp
  public/assets/images/trendMovieImages/trendMovie09.webp
  public/assets/images/trendMovieImages/trendMovie10.webp
Labels: 💫 FEAT, 🍀FE

#67 feat: 영화 상세페이지 모달 api 연동
  app/(anon)/movie-detail/components/MovieDetailModal.tsx
  app/(anon)/movie-detail/components/MovieHeader.tsx
  app/(anon)/movie-detail/components/MoviePreviewInfo.tsx
  app/components/Platform.ts
  utils/tmdb/TmdbApi.ts
Labels: 💫 FEAT, 🍀FE

#74 design: UI 틀어진 부분 수정
  app/(anon)/recommender/page.tsx
  app/page.tsx
Labels: 🍀FE

#75 feat: 검색 페이지 API 연동
  README.md
  app/(anon)/search/artist/page.tsx
  app/(anon)/search/components/RecommendedMovieList.tsx
  app/(anon)/search/components/SearchResult.tsx
  app/api/(anon)/search/person/[id]/credits/route.ts
  app/api/(anon)/search/trending/route.ts
  app/components/CircleCard.tsx
  package.json
  utils/tmdb/TmdbApi.ts
Labels: 🐞BUG, 🔥BE, 🍀FE

#81 fix: 캘린더 데이터 캐싱로직 삭제
  app/api/(anon)/saves/route.ts
Labels: 🐞BUG, 🔥BE

#86 fix: 찜하기, 댓글 조회 api 요청별 인증 여부 분리
  app/api/(anon)/saved-watch/route.ts
  app/constants/authPaths.ts
  app/middleware.ts
  utils/axios.ts
Labels: 🐞BUG, 🔥BE
